# Generated by Django 4.2.4 on 2023-08-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birt_of_date',
            new_name='birth_of_date',
        ),
    ]
