# Generated by Django 4.2.4 on 2023-08-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_rename_birt_of_date_student_birth_of_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birth_of_date',
            new_name='date_of_birth',
        ),
    ]
