# Generated by Django 4.2.4 on 2023-08-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='name',
        ),
    ]
