# Generated by Django 4.2.4 on 2023-08-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_rename_subject_subject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject',
        ),
    ]
